### ISSUE TITLE
Bouncer(?) animation bug

### ISSUE THREAD

**Issue by Draco18s** [k4zmu2a/SpaceCadetPinball#141] opened 2022-06-14 20:19 UTC
https://youtu.be/pGUD52cYSeE?t=14

Not even sure how to describe the behavior, other than the bouncer appears to trigger, but doesn't actually give the ball a kick.

I think that this is a situation where the physics is correct, but the bouncer shouldn't animate (ball is rolling along the rubber band but doesn't come in with enough force to trigger the leaf switches).

Cleanest comparable example I could find from the original
https://youtu.be/uMZwb05pPnI?t=71

**Comment by k4zmu2a** [comment] 2022-06-15 06:14
This was a very fresh bug introduced by careless refactoring last month.
Caused by confusion between “soft” and “hard” collision.
Fixed in V2, not present in V1.

**Comment by Draco18s** [comment] 2022-06-15 15:11
Makes sense.Certainly doesn't affect play, just looks weird.

**Comment by k4zmu2a** [comment] 2023-10-16 07:18
Released in V2.1.0

**Closed by k4zmu2a** 2023-10-16 07:18 UTC
Labels: bug
