### ISSUE TITLE
MIDI fix for WINE

### ISSUE THREAD

**Issue by parkerlreed** [k4zmu2a/SpaceCadetPinball#3] opened 2021-08-12 23:55 UTC
Was wondering why none of the fixes for MIDI playback in WINE were working. Turns out this is a "bug" with the original code (mci.c in WINE is partly to blame but it looks like the fix never got merged upstream)

https://www.winehq.org/pipermail/wine-bugs/2019-January/507548.html

I want to test messing with SpaceCadetPinball/midi.cpp but I have no idea how I would compile this from Linux.

**Comment by 0n1cOn3** [comment] 2021-08-14 05:09
The whole GUI is missing for a cross-platform compile. Like GTK or QT Support..

**Comment by GeorgeMcMullen** [comment] 2021-08-16 12:42
I had encountered this issue while getting Space Cadet running in WINE on Raspberry Pi with Box86. At the end of the day, I patched the Space Cadet binary to call the Windows MIDI framework correctly, so I could use it with any version of Wine. I've implemented the same fix in the code here and posted a pull request.

https://github.com/k4zmu2a/SpaceCadetPinball/pull/5

**Comment by parkerlreed** [comment] 2021-08-17 01:40
@GeorgeMcMullen Brilliant! Exactly what I was thinking of. Thanks.

**Comment by parkerlreed** [comment] 2021-08-17 01:45
@GeorgeMcMullen Along the same lines of audio issues, have you encountered the popping audio for sound effects? Both Pipewire and Pulse (With WINE set to either pulse or alsa) have some pretty bad pop in/outs when the sound effects play. 

https://user-images.githubusercontent.com/841440/129650479-b211a91e-98ef-4133-9a47-1e4f9912501f.mp4

Curious if it's just how the audio function is being called or what.

**Comment by GeorgeMcMullen** [comment] 2021-08-17 05:37
Yes, I also experienced some audio issues with the sound effects. While it was before this project became available, and I was using Box86 on a Raspberry Pi with WINE (set to ALSA), I think my findings might still apply. In the typical Space Cadet installation, there is a file called `wavemix.inf`. This is an audio engine that predates Direct Sound. You can find out more information about it here: https://www.compuphase.com/wavemix.htm

The original `wavemix.inf` file has some documentation in it as well. I twiddled with the settings until I came up with something that sounded decent. Below is my version of the `wavemix.inf` file. Perhaps it will work for you as well.

```
[general]
ShowDevices=0
WaveOutDevice=0
[default]
Remix=2
GoodWavePos=1
WaveBlocks=6
WaveBlockLen=688
SamplesPerSec=44
```

**Comment by parkerlreed** [comment] 2021-08-17 22:01
Thanks. A LOT less pops. I'll try messing around with that later to see if I can improve it any more.

**Comment by parkerlreed** [comment] 2021-08-17 22:07
I found a partial fix. The resampling takes enough time to cause the pops

```
 (+) Audio --aid=1 (pcm_u8 1ch 11025Hz)
```

Resampling the audio beforehand works but this causes a new bug. The intro sound plays but the ball never spawns. 

```
mkdir sounds
for i in *WAV; do ffmpeg -i $i -ar 48000 sounds/$i; done
cp sounds/* . 
```

**Comment by parkerlreed** [comment] 2021-08-17 22:21
Sorry for the spam... Good news! Audio pre resampled to 44100 and your wavemix.inf from above is perfect!

**Comment by parkerlreed** [comment] 2021-08-18 04:26
Well that was too good to be true. If you launch ramp in these conditions the ball is "stuck" until you lose focus and focus back.

![image](https://user-images.githubusercontent.com/841440/129836742-52521c57-4b11-43a8-9a3f-4c03b67633bb.png)

Also the popping seems to be hardware dependent. Sounded great on the laptop but same settings desktop I continue to hear the pop on sound effects.

**Comment by GeorgeMcMullen** [comment] 2021-08-18 07:29
Interesting! Are you playing on a 32bit OS / Wine or 64 bit? I wonder if some of the issues you are seeing are related to the issues Microsoft alluded to regarding hit detection when trying to convert the file to 64 bits. Also, have you tried the original Pinball executable to compare the results?

**Comment by parkerlreed** [comment] 2021-08-18 07:44
Yeah I think this is the same issue as the ball not spawning on launching the game after the 11025 to 44100 sound conversion. 

x64. Both x86 from this repo and original show the same beahvaior.

**Comment by GeorgeMcMullen** [comment] 2021-08-18 07:57
Some of the clicking may also indicate that additional compiler optimization is needed. Specifically with audio, it's common to have the compiler set to optimize to the max it can. We should also keep in mind that the original Space Cadet may have used a pre-compiled WaveMix library, which was already extremely optimized, and the decompilation and recompilation may have lost a few things in translation.

I've played with the new compile (x86) on my Raspberry Pi with Box86/Wine and it works well. I do hear minor pops here and there that I don't typically hear with the original executable. I'm using my wavemix.inf file and original audio files (not resampled). I vaguely remember trying to resample the audio files and having an issue with them, like you have, but it was over a year ago.

Good news though! My pull request for the MIDI fix has been accepted and merged. Hopefully we'll see a new build soon!

**Comment by parkerlreed** [comment] 2021-08-18 08:00
I noticed! Congrats. I'll close this out for now and may spawn another issue for the audio related fun. :)

**Closed** 2021-08-18 07:59 UTC

**Comment by k4zmu2a** [comment] 2021-08-18 08:03
Merged pull request #5.

On ball getting stuck with resampled audio: this is caused by wav duration approximation.
Ball release is tied to the end of sound that plays during startup sequence (light show).

The game uses formula: file length in bytes * 0.0000909090909090909 = duration in sec.
See https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/SpaceCadetPinball/loader.cpp#L153.

This could be fixed by computing the duration from header, as seen here: https://stackoverflow.com/questions/23742286/computing-duration-of-a-wav-file.
I will try it later.

On audio issues:
Have you tried running original win game and/or this project with Full Tilt cadet data?
I might have lost something in decompilation of WaveMix.

Some info on sound API used:
Original win game uses WaveMix waveOut lib for wav and MCI for MIDI.
Original Full Tilt game uses DirectSound for wav and midiStream for MIDI.
This project copies win game with one exception: Full Tilt mode uses midiStream for MIDI.

**Comment by parkerlreed** [comment] 2021-08-18 15:42
@k4zmu2a Quite the contrary! The popping issue is on all versions (Windows, haven't tried Full Tilt). I think it's an oddity with how the wavemix is being handled by WINE in general. 

So as far as your decomp goes, it seems very faithful :)

Good to know Full Tilt original used DirectSound. I'll give that a shot. Might work better for WINE (and as you noted this is only in the original and not in the decomp since it's waveOut and midiStream for Full Tilt mode?)

**Comment by GeorgeMcMullen** [comment] 2021-08-18 19:07
> The game uses formula: file length in bytes * 0.0000909090909090909 = duration in sec.

@k4zmu2a  
How weird - that line of code doesn't even take into account the header data. Must have been just close enough. Perhaps that is one of the actual reasons for some of the pops. If a wave form starts or gets cut off at a peak amplitude (instead of 0 amplitude), it can produce clicks/pops. I saw your fix. Nice!

While in this day in age it seems strange that they would directly tie a sound effect to something that occurs in the game play, or perform those types of calculations, one has to remember that this was one of the early games on the new Windows operating systems. The operating system, programming languages, frameworks, and techniques weren't as fleshed out as they are now with things like event based programming, lambas, code blocks, etc. I'm always impressed at how some of this early code was able to accomplish so much and capture the hearts of the fans of games like this. It's even more impressive that the original code still mostly works without modification, almost 30 years later! Then to decompile, reverse engineer, fix and recompile the code like @k4zmu2a... Wow! Incredible.

I'm looking forward to seeing how this continues to evolve (and hopefully participating more too).

**Comment by parkerlreed** [comment] 2021-08-18 20:47
Woohoo! Maybe a new release is in order? I'm lost on building Windows stuff :D

**Comment by parkerlreed** [comment] 2021-08-19 01:07
Got the new release built. The ball startup sound and ball ready happens during the intro sound. 

No differences on pops. Probably down to weirdness with WINE. Hopefully the future cross-platform port can fill this gap. 

@k4zmu2a Thanks again for this project!

**Comment by k4zmu2a** [comment] 2021-08-19 06:57
I managed to reproduce some of the pops on Windows with this .ini and stock Win version sounds:
```
[default]
SamplesPerSec=44
```
As it turns out, there was a bug in WaveMix up-sampler, introduced by me.
Fixing it does not help with WINE problems, but should remove the need for manual up-sampling. 

I also made a bug fix release.
